### PR TITLE
OCPQE-19029 OCPQE-19030  JSON schema prototype design and file parser impl

### PR DESCRIPTION
**Pull request by rioliu-rh**
design prototype

- one release one file under dir _releases like `ocp-4.15-test-jobs.json`
- json schema contains object required jobs for both nightly and stable build, it contains all the prow job objects. the object contains job name and the other control flags `disabled`, `optional`, `upgrade`
- impl file parser to get test jobs
- call https://github.com/openshift/release-tests/blob/master/prow/job/job.py to trigger e2e/upgrade jobs
- support to get latest nightly and stable build

### CODE REVIEW

**Comment by rioliu-rh** [comment]
/retitle OCPQE-19029 OCPQE-19030  JSON schema prototype design and file parser impl

**Comment by jianzhangbjz** [comment]
I guess we don't need the `required/optional` level, and we can add `optional`  field for each prowjob, like below, what do you think?
```json
{
	"nightly": {
		"aws-c2s-ipi-disconnected-private-fips": {
			"optional": true,    // if true, ignore the test results. The default is false 
			"prowjob": "periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-aws-c2s-ipi-disconnected-private-fips-f14"
		},
		"amd64-nightly-azure-ipi-workers-rhel8": {
			"prowjob": "periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-azure-ipi-workers-rhel8-f14",
			"disabled": true // if true, skip it
		},
		"aws-ipi-disconnected-sts-basecap-none": {
			"prowjob": "periodic-ci-openshift-openshift-tests-private-release-4.16-amd64-nightly-4.16-upgrade-from-stable-4.15-aws-ipi-disconnected-sts-basecap-none-f28",
			"upgrade": true,
			"maxRetries": 3
		}
	},

	"stable": {}
}
```

**Comment by rioliu-rh** [comment]
@jianzhangbjz code is updated, can you review again.thx

**Pull request merged**
