### PR TITLE
OCPQE-18902 don't fail cmd update-bug-list when got unauthorized error

### PR DESCRIPTION
**Pull request by rioliu-rh**
follow up PR for https://github.com/openshift/release-tests/pull/127
```console
$ oar -r 4.14.9 update-bug-list --no-notify
2024-01-15T13:34:41Z: INFO: task [Bug to be verified] status is changed to [In Progress]
2024-01-15T13:35:58Z: INFO: found existing bug OCPBUGS-22747 in report, checking...
2024-01-15T13:36:00Z: INFO: status of bug OCPBUGS-22747 is updated to Verified
2024-01-15T13:36:00Z: INFO: found existing bug OCPBUGS-24423 in report, checking...
2024-01-15T13:36:01Z: INFO: bug status of OCPBUGS-24423 is not changed
2024-01-15T13:36:02Z: INFO: found existing bug OCPBUGS-26003 in report, checking...
2024-01-15T13:36:03Z: INFO: status of bug OCPBUGS-26003 is updated to Verified
2024-01-15T13:36:04Z: INFO: found existing bug OCPBUGS-26214 in report, checking...
2024-01-15T13:36:04Z: INFO: bug status of OCPBUGS-26214 is not changed
2024-01-15T13:36:05Z: INFO: found existing bug OCPBUGS-26421 in report, checking...
2024-01-15T13:36:05Z: INFO: bug status of OCPBUGS-26421 is not changed
2024-01-15T13:36:19Z: ERROR: Cannot get jira issue OCPBUGS-26519 due to permission issue
Traceback (most recent call last):
  File "/Users/rio.liu/coderepo/release-tests/oar/core/jira_mgr.py", line 44, in get_issue
    issue = self._svc.issue(key)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jira/client.py", line 1468, in issue
    issue.find(id, params=params)
  File "/usr/local/lib/python3.11/site-packages/jira/resources.py", line 294, in find
    self._find_by_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/jira/resources.py", line 309, in _find_by_url
    self._load(url, params=params)
  File "/usr/local/lib/python3.11/site-packages/jira/resources.py", line 479, in _load
    r = self._session.get(url, headers=headers, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jira/resilientsession.py", line 223, in request
    elif raise_on_error(response, **processed_kwargs):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jira/resilientsession.py", line 69, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 403 url: https://issues.redhat.com/rest/api/2/issue/OCPBUGS-26519
	text: You do not have the permission to see the specified issue.

	response headers = {'x-arequestid': '336x1052235x2', 'x-anodeid': 'rh1-jira-prod-0', 'referrer-policy': 'strict-origin-when-cross-origin', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'Content-Security-Policy': 'sandbox', 'strict-transport-security': 'max-age=31536000', 'x-seraph-loginreason': 'OK', 'X-RateLimit-Limit': '-1', 'X-RateLimit-Remaining': '9223372036854775807', 'x-ratelimit-fillrate': '-1', 'x-ratelimit-interval-seconds': '1', 'Retry-After': '0', 'x-asessionid': '198naj4', 'x-ausername': 'rhn-support-rioliu', 'Content-Encoding': 'gzip', 'Vary': 'User-Agent, Accept-Encoding', 'Content-Type': 'application/json;charset=UTF-8', 'Expires': 'Mon, 15 Jan 2024 05:36:19 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Mon, 15 Jan 2024 05:36:19 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive, Transfer-Encoding', 'Set-Cookie': 'JSESSIONID=06B7001EBB6869C21845A2B063D070E5; Path=/; Secure; HttpOnly, atlassian.xsrf.token=AQZJ-FV3A-N91S-UDEU_4e69cc46d55b861d80e305230596987baa52bf4a_lin; Path=/; Secure; SameSite=None', 'x-rh-edge-request-id': 'e5072776', 'x-rh-edge-reference-id': '0.457a4017.1705296979.e5072776', 'x-rh-edge-cache-status': 'NotCacheable from child'}
	response text = {"errorMessages":["You do not have the permission to see the specified issue."],"errors":{}}
2024-01-15T13:36:19Z: INFO: checking all bugs are verified
2024-01-15T13:36:20Z: INFO: result is: no
```

### CODE REVIEW

**Comment by rioliu-rh** [comment]
@jianzhangbjz Can you help to check the failed job , thanks
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release-tests/128/pull-ci-openshift-release-tests-master-images/1746807193346248704

**Comment by jianzhangbjz** [comment]
Hi @rioliu-rh , I guess you have to rebase the latest master branch so that the `images` test pass, thanks!

**Comment by jianzhangbjz** [comment]
That's odd. It still uses the old image `INFO[2024-01-16T03:04:18Z] Tagging openshift/release:rhel-9-release-golang-1.20-openshift-4.14 into pipeline:root. ` .

**Comment by jianzhangbjz** [comment]
I guess it's a GitHub bug, could you help reopen a new PR? Thanks!

**Pull request closed without merging**
